# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uXrDBf630_VZEJXmsBZQKfGGnsRUuLO2
"""

score = 0


q1 = input("1. What is the capital of India? ")


if q1 == "Delhi":
   print("Correct")
   score += 1

else:
    print("Wrong")


q2 = input("2. What is 5+5? ")


if q2 == "10":

   print("Correct")
   score += 1

else:
    print("Wrong")



q3 = input("3. Which language are you learning? ")

if q3 == "Python":
   print("Correct")
   score += 1

else:
    print("Wrong")



q4 = input("4. What is 14 * 14? ")

if q4 == "196":
   print("Correct")
   score += 1

else:
    print("Wrong")


q5 = input("5. What is 10 + 5? ")

if q5 == "15":
   print("Correct")
   score += 1

else:
    print("Wrong")

print("Final Score =", score, "5/5")